[HIMDBVersion]
2.0
[DATABASE_VERSION]
"1.1" 
[SESSIONS_]
"DefaultSession" 
"SimSession" 
[CONFIGURATIONS]
"Debug" 
"Release" 
"SimDebug_H8S-2600A" 
[CURRENT_CONFIGURATION]
"Debug" 
[CURRENT_SESSION]
"SimSession" 
[GENERAL_DATA_PROJECT]
"FDT_UserBootAreaFiles" "" 
[GENERAL_DATA_CONFIGURATION_Debug]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Debug]
"DefaultSession" 
"SimSession" 
[GENERAL_DATA_CONFIGURATION_Release]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_Release]
"DefaultSession" 
"SimSession" 
[GENERAL_DATA_CONFIGURATION_SimDebug_H8S-2600A]
"PROJECT_FILES_MODIFIED_DATA_TAG" "TRUE" 
[SESSIONS_SimDebug_H8S-2600A]
"DefaultSession" 
"SimSession" 
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_SimSession]
[GENERAL_DATA_SESSION_SimSession]
[GENERAL_DATA_SESSION_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_SimDebug_H8S-2600A_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Release_SimSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Release_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_SimDebug_H8S-2600A_SimSession]
[END]
